parser: "@babel/eslint-parser"
env:
  browser: true
  es6: true
  "jest/globals": true
extends:
  - 'eslint:recommended'
  - 'plugin:jest/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2020
  sourceType: module
ignorePatterns:
  - docs/
plugins:
  - jest
rules:
  indent:
    - error
    - tab
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console:
    - error
  no-prototype-builtins: off
  object-curly-spacing:
    - error
    - always
  jest/no-mocks-import:
    - error
